name: Artifact

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: bun install
      - run: bun run wasm --workspace=packages/pdfium
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pdfium-wasm
          path: |
            packages/pdfium/src/pdfium.js
            packages/pdfium/src/pdfium.wasm
